### ISSUE TITLE
Is TWRP compatible with cyanogenmod encryption?

### ISSUE THREAD

**Issue by msdos** [TeamWin/android_device_motorola_surnia#1]
I've encrypted my surnia phone using 13.0-20160517-NIGHTLY-surnia from cyanogenmod.

Using last twrp (3.0.2) `data` isn't mounted, not even a prompt asking for the pattern encryption is shown when I start TWRP.

Is this a bug in TWRP, or is it incompatible with cyanogenmod?

**Comment by 1763050296** [comment]
可以

**Comment by msdos** [comment]
Don't know if it's incompatible, but you can still update your nightly using adb sideload.

Check https://forum.cyanogenmod.org/topic/127843-cant-mount-encrypted-data-partition-in-recovery-no-prompt-for-pattern-unlock/?do=findComment&comment=611346
